version: '3.1'

services:
  node-red:
    image: nodered/node-red:1.2.6
    volumes:
      # - nodered:/data
      - '.:/data/node_modules/node-red-contrib-plex-ws'
    ports:
      - 1880:1880

volumes:
  nodered: {}
